using System;

namespace AdvancedGeology.WorldGen.ProceduralDeposits;

internal sealed class SparryMagnesitePlan : IAdditionalDepositPlan
{
    private const ulong Salt=0x5350415252594D47UL; private readonly int ox,oy,oz; private readonly double cs,ss,dip,seed; private readonly Fault[] faults; private readonly Manto[] mantos;
    private readonly record struct Fault(double Cs,double Ss,double Offset,double Phase);
    private readonly record struct Manto(double X,double Z,double Level,double Ra,double Rb,double Rv,double Phase);
    public int HorizontalRadius{get;} public int VerticalHalfHeight{get;} public int FaultCount=>faults.Length; public int MantoCount=>mantos.Length;
    private SparryMagnesitePlan(in ProceduralDepositInstance i,SparryMagnesiteDefinition s,double strike,double dip,double seed,Fault[] f,Manto[] m){ox=i.CenterX;oy=i.CenterY;oz=i.CenterZ;HorizontalRadius=s.HorizontalRadius;VerticalHalfHeight=s.VerticalHalfHeight;double r=strike*Math.PI/180;cs=Math.Cos(r);ss=Math.Sin(r);this.dip=dip;this.seed=seed;faults=f;mantos=m;}
    public static SparryMagnesitePlan Create(in ProceduralDepositInstance i,SparryMagnesiteDefinition s){var r=new ProceduralDepositRandom(i.FeatureId^Salt);double strike=r.Range(0,180),dip=r.Range(2,8),seed=r.Range(0,100);int fn=r.NextInt(s.FaultMin,s.FaultMax);var f=new Fault[fn];for(int k=0;k<fn;k++){double a=(strike+r.Range(-35,35))*Math.PI/180;f[k]=new(Math.Cos(a),Math.Sin(a),r.Range(-17,17),seed+k*17);}double[] levels=[-13,-2,9];int mn=r.NextInt(s.MantoMin,s.MantoMax);var m=new Manto[mn];double sr=strike*Math.PI/180,cs=Math.Cos(sr),ss=Math.Sin(sr);for(int k=0;k<mn;k++){double level=levels[k%3]+r.Range(-2,2),along=r.Range(-14,14);var q=f[k%fn];m[k]=new(along*q.Cs+q.Offset*q.Ss,-along*q.Ss+q.Offset*q.Cs,level,r.Range(13,22),r.Range(6,11),r.Range(2.2,4),seed+k*23);}return new(i,s,strike,dip,seed,f,m);}
    private (double a,double c) Local(double x,double z)=>(x*cs-z*ss,x*ss+z*cs);
    private double StratY(double x,double y,double z){var p=Local(x,z);return y-Math.Tan(dip*Math.PI/180)*p.c-Math.Sin(p.a*.06+seed)*1.1;}
    public AdditionalDepositSample Evaluate(int wx,int wy,int wz){double x=wx-ox,y=wy-oy,z=wz-oz;var lp=Local(x,z);double warp=1.1*Math.Sin(lp.a*.08+seed)+.7*Math.Cos(lp.c*.11-seed*.3);if(lp.a*lp.a/900+lp.c*lp.c/729+(y+2+warp)*(y+2+warp)/625>1)return default;double sy=StratY(x,y,z),fd=9;foreach(var f in faults){var p=Local(x,z);double d=Math.Abs(x*f.Ss+z*f.Cs-f.Offset-Math.Sin(p.a*.12+y*.08+f.Phase)*1.1),v=AdditionalDepositMath.Clamp(1-Math.Abs(y+3)/30,0,1);fd=Math.Min(fd,d/(1.1+.8*v));}double best=99;bool near=false;foreach(var m in mantos){var p=Local(x-m.X,z-m.Z);double u=p.a/m.Ra,v=p.c/m.Rb,w=(sy-m.Level)/m.Rv,r=Math.Sqrt(u*u+v*v+w*w)+.1*Math.Sin(u*4+m.Phase)*Math.Cos(v*3.1);if(r<best)best=r;if(r<1.32)near=true;}double field=Math.Sin(x*.17-z*.14+seed)+.45*Math.Cos(y*.25),feed=AdditionalDepositMath.Clamp(1-fd,0,1);if(best<1){if(best<.5+feed*.12)return new(ProceduralMaterialSlots.Magnesite,3);if(best<.76)return new(ProceduralMaterialSlots.Magnesite,1);if(best<.93)return field>.3?new(ProceduralMaterialSlots.Quartz):new(ProceduralMaterialSlots.Magnesite,0,.45);return default;}if(fd<.72&&sy<14){if(fd<.35)return Math.Sin(y*.31+seed)>.1?new(ProceduralMaterialSlots.Magnesite,3):new(ProceduralMaterialSlots.Magnesite,1);return default;}return near?default:default;}
}

internal sealed class CryptocrystallineMagnesitePlan : IAdditionalDepositPlan
{
    private const ulong Salt=0x43525950544F4D47UL; private readonly int ox,oy,oz;private readonly double cx,cz,rx,rz,seed;private readonly CxVein[] veins;private readonly Pod[] pods;
    private readonly record struct CxVein(double Cs,double Ss,double Sd,double Cd,double Off,double Cy,double Len,double H,double W,double P);
    private readonly record struct Pod(double X,double Y,double Z,double Rx,double Ry,double Rz,double P);
    public int HorizontalRadius{get;}public int VerticalHalfHeight{get;}public int VeinCount=>veins.Length;public int PodCount=>pods.Length;
    private CryptocrystallineMagnesitePlan(in ProceduralDepositInstance i,CryptocrystallineMagnesiteDefinition s,double cx,double cz,double rx,double rz,double seed,CxVein[] v,Pod[] p){ox=i.CenterX;oy=i.CenterY;oz=i.CenterZ;HorizontalRadius=s.HorizontalRadius;VerticalHalfHeight=s.VerticalHalfHeight;this.cx=cx;this.cz=cz;this.rx=rx;this.rz=rz;this.seed=seed;veins=v;pods=p;}
    public static CryptocrystallineMagnesitePlan Create(in ProceduralDepositInstance i,CryptocrystallineMagnesiteDefinition s){var r=new ProceduralDepositRandom(i.FeatureId^Salt);double cx=r.Range(-3,3),cz=r.Range(-3,3),rx=r.Range(26,31),rz=r.Range(22,28),seed=r.Range(0,100);int vn=r.NextInt(s.VeinMin,s.VeinMax);var v=new CxVein[vn];for(int k=0;k<vn;k++){double sr=r.Range(0,180)*Math.PI/180,dr=r.Range(55,88)*Math.PI/180;v[k]=new(Math.Cos(sr),Math.Sin(sr),Math.Sin(dr),Math.Cos(dr),r.Range(-20,20),r.Range(-7,4),r.Range(14,27),r.Range(16,28),r.Range(1.1,2.5),seed+k*17);}int pn=r.NextInt(s.PodMin,s.PodMax);var p=new Pod[pn];for(int k=0;k<pn;k++)p[k]=new(r.Range(-20,20),r.Range(-18,10),r.Range(-18,18),r.Range(3,7),r.Range(3,8),r.Range(3,7),seed+k*23);return new(i,s,cx,cz,rx,rz,seed,v,p);}
    public AdditionalDepositSample Evaluate(int wx,int wy,int wz){double x=wx-ox,y=wy-oy,z=wz-oz,warp=1.2*Math.Sin(x*.08+seed)+.8*Math.Cos(z*.1-seed*.35);if((x-cx)*(x-cx)/841+(z-cz)*(z-cz)/676+(y+4+warp)*(y+4+warp)/529>1)return default;double u=(x-cx)/rx,v=(z-cz)/rz,w=(y+4)/31,mass=Math.Sqrt(u*u+v*v+.35*w*w)+.08*Math.Sin(u*4+seed)*Math.Cos(v*3.5);if(mass>=1)return default;bool core=false,halo=false;double min=9;foreach(var q in veins){double a=x*q.Cs-z*q.Ss,c=x*q.Ss+z*q.Cs-q.Off,dy=y-q.Cy,b=Math.Sin(a*.13+y*.07+q.P)*1.2,sd=c*q.Sd+dy*q.Cd-b,un=a/q.Len,qn=dy/q.H,foot=Math.Sqrt(un*un+qn*qn),tap=AdditionalDepositMath.Clamp(1-foot*foot,0,1),dist=Math.Abs(sd),half=q.W*.5*Math.Sqrt(tap),ratio=dist/Math.Max(.1,half);if(foot<1&&dist<half){core=true;min=Math.Min(min,ratio);}if(foot<1.1&&dist<half+3*Math.Sqrt(Math.Max(tap,.04)))halo=true;}double best=99;bool ph=false;foreach(var p in pods){double pu=(x-p.X)/p.Rx,pv=(y-p.Y)/p.Ry,pw=(z-p.Z)/p.Rz,pr=Math.Sqrt(pu*pu+pv*pv+pw*pw)+.08*Math.Sin(pu*4+p.P)*Math.Cos(pw*3);best=Math.Min(best,pr);if(pr<1.35)ph=true;}double f=Math.Sin(x*.22-z*.17+seed)+.5*Math.Cos(y*.29+x*.05);if(best<1){if(best<.55)return new(ProceduralMaterialSlots.Magnesite,3);if(best<.8)return f>.05?new(ProceduralMaterialSlots.Magnesite,3):new(ProceduralMaterialSlots.Magnesite,1);return new(ProceduralMaterialSlots.Soapstone);}if(core){if(min<.5)return f>-.55?new(ProceduralMaterialSlots.Magnesite,3):new(ProceduralMaterialSlots.Magnesite,1);return f>.45?new(ProceduralMaterialSlots.Quartz):new(ProceduralMaterialSlots.Magnesite,1);}if(halo||ph)return new(ProceduralMaterialSlots.Soapstone);double freshness=1-mass,olivineField=Math.Sin((x-cx)*.13+(z-cz)*.11+(y+4)*.09+seed);if(freshness>.28&&olivineField>.32)return new(ProceduralMaterialSlots.Olivine);return default;}
}
