using System;

namespace AdvancedGeology.WorldGen.ProceduralDeposits;

/// <summary>
/// Pyrochlore, monazite, bastnasite, xenotime, zircon, fluorite, quartz, feldspar, and sodalite occupy pegmatite sheets and fracture halos beneath an uplifted peralkaline pluton roof.
/// </summary>
internal sealed class PeralkalineHreePlan : IAdditionalDepositPlan
{
    private const ulong Salt=0x504552414C4B4852UL;private readonly int ox,oy,oz;private readonly double cx,cz,rx,rz,roof,floor,ex,ez,erx,erz,rise,diffDepth,seed;private readonly Peg[] pegs;private readonly Frac[] fracs;
    private readonly record struct Peg(double X,double Z,double Y,double Rx,double Rz,double Half,double Tilt,double Phase);
    private readonly record struct Frac(double Cs,double Ss,double Sd,double Cd,double Offset,double Y,double Length,double Height,double Width,double Phase);
    public int HorizontalRadius{get;}public int VerticalHalfHeight{get;}public int PegmatiteCount=>pegs.Length;public int FractureCount=>fracs.Length;
    private PeralkalineHreePlan(in ProceduralDepositInstance i,PeralkalineHreeDefinition s,double cx,double cz,double rx,double rz,double roof,double floor,double ex,double ez,double erx,double erz,double rise,double dd,double seed,Peg[] p,Frac[] f){ox=i.CenterX;oy=i.CenterY;oz=i.CenterZ;HorizontalRadius=s.HorizontalRadius;VerticalHalfHeight=s.VerticalHalfHeight;this.cx=cx;this.cz=cz;this.rx=rx;this.rz=rz;this.roof=roof;this.floor=floor;this.ex=ex;this.ez=ez;this.erx=erx;this.erz=erz;this.rise=rise;diffDepth=dd;this.seed=seed;pegs=p;fracs=f;}
    public static PeralkalineHreePlan Create(in ProceduralDepositInstance i,PeralkalineHreeDefinition s){var r=new ProceduralDepositRandom(i.FeatureId^Salt);double cx=r.Range(-4,4),cz=r.Range(-4,4),rx=r.Range(23,29),rz=r.Range(19,25),roof=r.Range(9,15),floor=r.Range(-29,-24),ex=cx+r.Range(-9,9),ez=cz+r.Range(-8,8),erx=r.Range(9,14),erz=r.Range(8,12),rise=r.Range(5,9),dd=r.Range(22,30),seed=r.Range(0,100);int pn=r.NextInt(s.PegmatiteMin,s.PegmatiteMax);var p=new Peg[pn];for(int k=0;k<pn;k++){double t=k/Math.Max(1.0,pn-1);p[k]=new(ex+r.Range(-8,8),ez+r.Range(-7,7),roof-2-t*r.Range(5,9)-r.Range(0,3),r.Range(9,15),r.Range(8,13),r.Range(1.6,2.8),r.Range(-.07,.07),seed+k*23.4);}int fn=r.NextInt(s.FractureMin,s.FractureMax);var f=new Frac[fn];for(int k=0;k<fn;k++){double sr=r.Range(0,Math.PI),dr=r.Range(66,86)*Math.PI/180;f[k]=new(Math.Cos(sr),Math.Sin(sr),Math.Sin(dr),Math.Cos(dr),r.Range(-16,16),r.Range(-10,8),r.Range(14,24),r.Range(14,24),r.Range(1.1,2.2),seed+61+k*17.7);}return new(i,s,cx,cz,rx,rz,roof,floor,ex,ez,erx,erz,rise,dd,seed,p,f);}
    private double Roof(double x,double z){double dx=(x-ex)/erx,dz=(z-ez)/erz,fp=Math.Sqrt(dx*dx+dz*dz),y=roof+.03*x-.022*z+Math.Sin(x*.055+seed*.6)*1.5+Math.Cos(z*.048-seed*.3)*1.2;if(fp<1)y+=rise*(1-fp*fp);return y;}
    private (bool inside,double lateral,double roof,double below) Pluton(double x,double y,double z){double u=(x-cx)/rx,v=(z-cz)/rz,warp=.08*Math.Sin(u*4.1+seed)*Math.Cos(v*3.4)+.04*Math.Sin((u-v)*6.2-seed*.4),lat=Math.Sqrt(u*u+v*v)+warp,ry=Roof(x,z);return(lat<=1&&y<=ry&&y>=floor,lat,ry,ry-y);}
    private (bool inside,double w) PegHit(double x,double y,double z,Peg p){double u=(x-p.X)/p.Rx,v=(z-p.Z)/p.Rz,foot=Math.Sqrt(u*u+v*v)+.08*Math.Sin(u*4+p.Phase)*Math.Cos(v*3),tap=AdditionalDepositMath.Clamp(1-foot*foot,0,1),mid=p.Y+p.Tilt*(x-p.X),half=.35+p.Half*Math.Sqrt(tap),w=Math.Abs(y-mid)/Math.Max(.35,half);return(foot<=1.03&&w<=1,w);}
    private (bool core,bool halo) FracHit(double x,double y,double z,Frac f){double along=x*f.Cs-z*f.Ss,across=x*f.Ss+z*f.Cs-f.Offset,vertical=y-f.Y,bend=Math.Sin(along*.15+y*.08+f.Phase)*1.2,signed=across*f.Sd+vertical*f.Cd-bend,u=along/f.Length,v=vertical/f.Height,foot=Math.Sqrt(u*u+v*v),tap=AdditionalDepositMath.Clamp(1-foot*foot,0,1),d=Math.Abs(signed);return(foot<=1&&d<=f.Width*Math.Sqrt(tap),foot<=1.1&&d<=(f.Width+1.8)*Math.Sqrt(Math.Max(tap,.05)));}
    public AdditionalDepositSample Evaluate(int wx,int wy,int wz){double x=wx-ox,y=wy-oy,z=wz-oz;var p=Pluton(x,y,z);if(!p.inside)return default;double dx=(x-ex)/erx,dz=(z-ez)/erz,emb=AdditionalDepositMath.Clamp(1-Math.Sqrt(dx*dx+dz*dz),0,1),depth=AdditionalDepositMath.Clamp(1-p.below/diffDepth,0,1),diff=AdditionalDepositMath.Clamp(depth*(1-.5*p.lateral)+.35*emb,0,1.35),band=Math.Sin(x*.19+seed)+Math.Cos(z*.21-seed*.4)+.55*Math.Sin(y*.24+x*.05);bool ac=false,ah=false;foreach(var f in fracs){var h=FracHit(x,y,z,f);ac|=h.core;ah|=h.halo&&!h.core;}bool found=false;double bw=99;foreach(var g in pegs){var h=PegHit(x,y,z,g);if(h.inside&&h.w<bw){found=true;bw=h.w;}}if(found){bool altered=ac||ah||diff>.82;if(bw<.42){if(band>.85)return new(ProceduralMaterialSlots.Fluorite);if(band<-.85)return new(ProceduralMaterialSlots.Bastnasite,2);return new(ProceduralMaterialSlots.Quartz);}if(bw<.72){if(altered)return band>.35?new(ProceduralMaterialSlots.Gittinsite,2):new(ProceduralMaterialSlots.Xenotime,2);if(band>.35)return new(ProceduralMaterialSlots.Fluorite);return new(ProceduralMaterialSlots.Quartz);}if(altered)return band>.25?new(ProceduralMaterialSlots.Xenotime,3):new(ProceduralMaterialSlots.Gittinsite,3);if(band>.55)return new(ProceduralMaterialSlots.Pyrochlore,2);if(band>-.35)return new(ProceduralMaterialSlots.Zirconia);return new(ProceduralMaterialSlots.Matrix);}if(ac&&diff>.42){if(diff>.78)return band>.45?new(ProceduralMaterialSlots.Gittinsite,3):new(ProceduralMaterialSlots.Xenotime,3);if(band>.75)return new(ProceduralMaterialSlots.Gittinsite,2);if(band>-.25)return new(ProceduralMaterialSlots.Xenotime,2);return new(ProceduralMaterialSlots.Hematite,0);}if(ah&&diff>.62)return band>.15?new(ProceduralMaterialSlots.Xenotime,1):new(ProceduralMaterialSlots.Hematite,0);if(diff>.62){if(band>1.02)return new(ProceduralMaterialSlots.Pyrochlore,2);if(band>.52)return new(ProceduralMaterialSlots.Zirconia);return new(ProceduralMaterialSlots.Matrix);}if(diff>.34)return band>1.24?new(ProceduralMaterialSlots.Zirconia):new(ProceduralMaterialSlots.Matrix);return new(ProceduralMaterialSlots.Matrix);}
}
