using System;

namespace AdvancedGeology.WorldGen.ProceduralDeposits;

/// <summary>
/// Uraninite, quartz, hematite, clay, graphite, and secondary uranium minerals form an unconformity-bound lens with a fault-rooted feeder and smaller perched lenses.
/// </summary>
internal sealed class UnconformityUraniumPlan : IAdditionalDepositPlan
{
    private const ulong Salt=0x554E434F4E465552UL; private readonly int ox,oy,oz;private readonly double uncBase,tx,tz,seed;private readonly UFault[] faults;private readonly Lens main;private readonly Root root;private readonly Lens[] perched;
    private readonly record struct UFault(double Cs,double Ss,double Sd,double Cd,double Offset,double Cy,double Length,double Height,double Width,double Phase);
    private readonly record struct Lens(double X,double Y,double Z,double Cs,double Ss,double Ra,double Rc,double Rv,double Phase);
    private readonly record struct Root(double Top,double Bottom,double Along,double Half,double Phase);
    public int HorizontalRadius{get;}public int VerticalHalfHeight{get;}public int FaultCount=>faults.Length;public int PerchedCount=>perched.Length;
    private UnconformityUraniumPlan(in ProceduralDepositInstance i,UnconformityUraniumDefinition s,double ub,double tx,double tz,double seed,UFault[] f,Lens m,Root root,Lens[] p){ox=i.CenterX;oy=i.CenterY;oz=i.CenterZ;HorizontalRadius=s.HorizontalRadius;VerticalHalfHeight=s.VerticalHalfHeight;uncBase=ub;this.tx=tx;this.tz=tz;this.seed=seed;faults=f;main=m;this.root=root;perched=p;}
    public static UnconformityUraniumPlan Create(in ProceduralDepositInstance i,UnconformityUraniumDefinition s){var r=new ProceduralDepositRandom(i.FeatureId^Salt);double ub=r.Range(1,7),tx=r.Range(-.05,.05),tz=r.Range(-.04,.04),strike=r.Range(0,180),dip=r.Range(52,76),seed=r.Range(0,100);double sr=strike*Math.PI/180,cs=Math.Cos(sr),ss=Math.Sin(sr);int sn=r.NextInt(s.SplayMin,s.SplayMax);var f=new UFault[sn+1];f[0]=Make(strike,dip,r.Range(-5,5),r.Range(-8,-1),r.Range(24,32),r.Range(24,32),r.Range(2.2,3.4),seed);for(int k=0;k<sn;k++)f[k+1]=Make(strike+r.Range(-26,26),dip+r.Range(-10,10),f[0].Offset+(k%2==0?-1:1)*r.Range(4,9),r.Range(-14,-4),r.Range(14,22),r.Range(16,24),r.Range(1.3,2.2),seed+41+k*13);double gx=f[0].Offset*ss,gz=f[0].Offset*cs,la=r.Range(-6,6),lx=gx+la*cs,lz=gz-la*ss,ly=Unc(ub,tx,tz,seed,lx,lz);var m=new Lens(lx,ly-r.Range(.5,2.5),lz,cs,ss,r.Range(11,17),r.Range(4,6.5),r.Range(2.6,4.2),seed+7.3);var root=new Root(m.Y+1.5,r.Range(-29,-24),lx*cs-lz*ss,r.Range(8,12),seed+53);int pn=r.NextInt(s.PerchedMin,s.PerchedMax);var p=new Lens[pn];for(int k=0;k<pn;k++){double px=lx+r.Range(-7,7),pz=lz+r.Range(-6,6);p[k]=new(px,Unc(ub,tx,tz,seed,px,pz)+r.Range(5,12),pz,cs,ss,r.Range(4,7),r.Range(2.4,4),r.Range(1.4,2.4),seed+83+k*9);}return new(i,s,ub,tx,tz,seed,f,m,root,p);}
    private static UFault Make(double s,double d,double o,double cy,double l,double h,double w,double p){double sr=s*Math.PI/180,dr=d*Math.PI/180;return new(Math.Cos(sr),Math.Sin(sr),Math.Sin(dr),Math.Cos(dr),o,cy,l,h,w,p);}
    private static double Unc(double b,double x,double z,double seed,double px,double pz)=>b+x*px+z*pz+Math.Sin(px*.052+seed*.5)*1.7+Math.Cos(pz*.06-seed*.35)*1.4;
    private (bool core,bool halo,double d,double half,double foot,double along) Fault(double x,double y,double z,UFault f){double along=x*f.Cs-z*f.Ss,across=x*f.Ss+z*f.Cs-f.Offset,vertical=y-f.Cy,bend=Math.Sin(along*.12+y*.06+f.Phase)*1.4,signed=across*f.Sd+vertical*f.Cd-bend,u=along/f.Length,w=vertical/f.Height,foot=Math.Sqrt(u*u+w*w),tap=AdditionalDepositMath.Clamp(1-foot*foot,0,1),d=Math.Abs(signed),half=f.Width*.5*Math.Sqrt(tap);return(foot<=1&&d<=half,foot<=1.1&&d<=(f.Width*.5+3.2)*Math.Sqrt(Math.Max(tap,.05)),d,half,foot,along);}
    private static (bool inside,bool halo,double r) Hit(double x,double y,double z,Lens l){double da=(x-l.X)*l.Cs-(z-l.Z)*l.Ss,dc=(x-l.X)*l.Ss+(z-l.Z)*l.Cs,u=da/l.Ra,v=dc/l.Rc,w=(y-l.Y)/l.Rv,warp=.1*Math.Sin(u*4.1+l.Phase)*Math.Cos(v*3.3)+.05*Math.Sin(w*4.6-l.Phase*.3),r=Math.Sqrt(u*u+v*v+w*w)+warp;return(r<=1,r<=1.3,r);}
    public AdditionalDepositSample Evaluate(int wx,int wy,int wz){double x=wx-ox,y=wy-oy,z=wz-oz;if(Math.Abs(x)>HorizontalRadius||Math.Abs(z)>HorizontalRadius||Math.Abs(y)>VerticalHalfHeight)return default;double unc=Unc(uncBase,tx,tz,seed,x,z);var mf=Fault(x,y,z,faults[0]);bool core=mf.core,halo=mf.halo;for(int k=1;k<faults.Length;k++){var f=Fault(x,y,z,faults[k]);core|=f.core;halo|=f.halo;}double band=Math.Sin(x*.23+seed)+Math.Cos(z*.21-seed*.5)+.6*Math.Sin(y*.27+x*.05);var mh=Hit(x,y,z,main);if(mh.inside){if(mh.r<.62)return new(ProceduralMaterialSlots.Uraninite,3);if(mh.r<.84)return band>-.35?new(ProceduralMaterialSlots.Uraninite,2):new(ProceduralMaterialSlots.Uraninite,1);return band>.3?new(ProceduralMaterialSlots.Quartz):new(ProceduralMaterialSlots.Uraninite,0);}if(y<=root.Top&&y>=root.Bottom&&mf.core){double depth=AdditionalDepositMath.Clamp((root.Top-y)/(root.Top-root.Bottom),0,1),tap=.58+.42*Math.Sin(Math.PI*depth),an=(mf.along-root.Along)/(root.Half*tap);if(Math.Abs(an)<=1){double shoot=Math.Cos(an*4.8+root.Phase)-.35*depth,ratio=mf.d/Math.Max(.1,mf.half);if(ratio<.42&&shoot>-.5)return new(ProceduralMaterialSlots.Uraninite,3);if(ratio<.92)return new(ProceduralMaterialSlots.Uraninite,1);return default;}}foreach(var p in perched){var h=Hit(x,y,z,p);if(h.inside){if(h.r<.55)return new(ProceduralMaterialSlots.Uraninite,1);return band>.25?new(ProceduralMaterialSlots.Quartz):default;}}if(y<=unc){double rd=unc-y;if(core){if(rd<4)return new(ProceduralMaterialSlots.Hematite,0);if(band>.55)return new(ProceduralMaterialSlots.Quartz);return default;}if(rd<3.2)return new(ProceduralMaterialSlots.Hematite,0);return default;}double above=y-unc,pr=3.5+.85*above,da=(x-main.X)*main.Cs-(z-main.Z)*main.Ss,dc=(x-main.X)*main.Ss+(z-main.Z)*main.Cs,pd=Math.Sqrt(da*da/(1.9*1.9)+dc*dc);if(above<26&&pd<pr)return core&&above<9&&band>.75?new(ProceduralMaterialSlots.Quartz):default;if(core&&above<12)return band>.4?new(ProceduralMaterialSlots.Quartz):default;return default;}
}
